theme = "kanagawa"

[editor]
auto-format = false
bufferline = "multiple"
color-modes = true
line-number = "relative"
mouse = true
rulers = [100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "┆"
render = true
skip-levels = 1

[editor.lsp]
display-inlay-hints = true

[editor.whitespace.characters]
newline = "⏎"
space = "·"
tab = "→"
tabpad = "·"

[editor.whitespace.render]
newline = "none"
space = "all"
tab = "all"

# Open yazi
[keys.normal]
C-y = [
    ':sh rm -f /tmp/unique-file',
    ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
    ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
    ':open %sh{cat /tmp/unique-file}',
    ':redraw',
    ':set mouse false',
    ':set mouse true',
]

# Drag selection
[keys.select]
A-k = [
    "yank_main_selection_to_clipboard",
    "delete_selection",
    "move_line_up",
    "paste_clipboard_before",
    "select_mode",
]

A-j = [
    "yank_main_selection_to_clipboard",
    "delete_selection",
    "move_line_down",
    "paste_clipboard_before",
    "select_mode",
]
