theme = "kanagawa"

[editor]
scrolloff = 999
auto-format = false
bufferline = "multiple"
color-modes = true       # cursorline mode indicator changes color
line-number = "relative"
mouse = true
rulers = [100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
render = true
skip-levels = 1

[editor.lsp]
display-inlay-hints = true

[editor.whitespace.characters]
newline = "⏎"
space = "·"
tab = "→"
tabpad = "·"

[editor.whitespace.render]
newline = "none"
space = "none"
tab = "all"
tabpad = "all"

# Open yazi
[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

A-k = [
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "move_line_up",
  "paste_clipboard_before",
  "select_mode",
]

A-j = [
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "move_line_down",
  "paste_clipboard_before",
  "select_mode",
]

C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]

# Drag selection
[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

A-k = [
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "move_line_up",
  "paste_clipboard_before",
  "select_mode",
]

A-j = [
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "move_line_down",
  "paste_clipboard_before",
  "select_mode",
]
