name: "NTFY Notify"
description: "Send notifications via NTFY for job success or failure"
inputs:
  topic:
    description: "NTFY topic to send notifications to"
    required: true
  url:
    description: "NTFY server URL"
    required: false
    default: "https://ntfy.sh"
  runs-on:
    description: "When to send notifications: success, failure, or both"
    required: false
    default: "both"

runs:
  using: "composite"
  steps:
    - name: Send notification
      if: |
        (inputs.runs-on == 'both') ||
        (inputs.runs-on == 'success' && job.status == 'success') ||
        (inputs.runs-on == 'failure' && job.status == 'failure')
      shell: bash
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          TITLE="[Github] Action Success"
          PRIORITY="4"
          TAGS="white_check_mark"
          MESSAGE="${{ github.workflow }} - ${{ matrix.system || 'build' }} successful
        Repo: ${{ github.repository }}
        Commit: ${{ github.sha }}"
          else
          TITLE="[Github] Action Failure"
          PRIORITY="5"
          TAGS="x"
          MESSAGE="${{ github.workflow }} - ${{ matrix.system || 'build' }} failed
        Repo: ${{ github.repository }}
        Commit: ${{ github.sha }}"
        fi

        curl -H "Title: $TITLE" \
          -H "Priority: $PRIORITY" \
          -H "Tags: $TAGS" \
          -H "Actions: view, Open Job, ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}, clear=true" \
          -d "$MESSAGE" \
          "${{ inputs.url }}/${{ inputs.topic }}"
