name: "NTFY Notify"
description: "Send notifications via NTFY for job success or failure"
inputs:
  topic:
    description: "NTFY topic to send notifications to"
    required: true
  url:
    description: "NTFY server URL"
    required: false
    default: "https://ntfy.sh"
  success-title:
    description: "Title for success notifications (defaults to workflow name + ' Successful')"
    required: false
    default: ""
  success-message:
    description: "Message for success notifications (defaults to workflow name + ' completed successfully!')"
    required: false
    default: ""
  failure-title:
    description: "Title for failure notifications (defaults to workflow name + ' Failed')"
    required: false
    default: ""
  failure-message:
    description: "Message for failure notifications (defaults to workflow name + ' failed!')"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Notify success
      if: job.status == 'success'
      shell: bash
      run: |
        TITLE="${{ inputs.success-title }}"
        MESSAGE="${{ inputs.success-message }}"

        # Use defaults if not provided
        if [ -z "$TITLE" ]; then
          TITLE="${{ github.workflow }} Successful"
        fi

        if [ -z "$MESSAGE" ]; then
          MESSAGE="${{ github.workflow }} completed successfully!"
        fi

        curl -H "Title: $TITLE" \
          -H "Priority: 4" \
          -H "Tags: white_check_mark" \
          -H "Actions: view, Open Job, ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}, clear=true" \
          -d "$MESSAGE" \
          "${{ inputs.url }}/${{ inputs.topic }}"

    - name: Notify failure
      if: job.status == 'failure'
      shell: bash
      run: |
        TITLE="${{ inputs.failure-title }}"
        MESSAGE="${{ inputs.failure-message }}"

        # Use defaults if not provided
        if [ -z "$TITLE" ]; then
          TITLE="${{ github.workflow }} Failed"
        fi

        if [ -z "$MESSAGE" ]; then
          MESSAGE="${{ github.workflow }} failed!"
        fi

        curl -H "Title: $TITLE" \
          -H "Priority: 5" \
          -H "Tags: x" \
          -H "Actions: view, Open Job, ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}, clear=true" \
          -d "$MESSAGE" \
          "${{ inputs.url }}/${{ inputs.topic }}"
