name: "NTFY Notify"
description: "Send notifications via NTFY"
inputs:
  topic:
    description: "NTFY topic to send notifications to"
    required: true
  url:
    description: "NTFY server URL"
    required: false
    default: "https://ntfy.sh"
  title:
    description: "Notification title"
    required: true
  priority:
    description: "Notification priority (1-5)"
    required: false
    default: "3"
  tags:
    description: "Notification tags (comma-separated)"
    required: false
    default: ""
  message:
    description: "Notification message"
    required: true
    default: ""
  button_url:
    description: "Button URL (defaults to current workflow run)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Send notification
      shell: bash
      run: |
        BUTTON_URL="${{ inputs.button_url }}"
        if [ -z "$BUTTON_URL" ]; then
          BUTTON_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        fi

        CURL_ARGS=(-H "Title: ${{ inputs.title }}" -H "Priority: ${{ inputs.priority }}")

        if [ -n "${{ inputs.tags }}" ]; then
          CURL_ARGS+=(-H "Tags: ${{ inputs.tags }}")
        fi

        CURL_ARGS+=(-H "Actions: view, Open, $BUTTON_URL, clear=true")
        CURL_ARGS+=(-d "${{ inputs.message }}")

        curl "${CURL_ARGS[@]}" "${{ inputs.url }}/${{ inputs.topic }}"
