keys:
  - &users
    - &angel age1xndmu8qplxwc6czlgv6amh2s7aujazcdv879r3fvhthh8xt6pfaqe75555
  - &hosts
    - &bengkui ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGWDiLLCEynlZVf1p2/I2+PotLTPtbirj6AeU5Nj4LeG
    - &nixos-vm age16ssscp6dgnpg8ev7enfqejkp2y0c00493rvgrh0vccwgdllk0y2swjawjq
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|sops)$
    key_groups:
    - age:
      - *angel
      - *bengkui
      - *nixos-vm
    # - path_regex: machines/nixos/[^/]+\.(yaml|json|env|ini|sops)$
    #   key_groups:
    #     - age:
    #       - *nixos-vm

  # Anything else not included above.
  - age: *angel
