{ config, pkgs, inputs, options, username, hostname, systemStateVersion, ... }:
let
  enableXServer = true;
in
{
  imports =
    [
      ./hardware.nix
      ../_default/nixos/configuration.nix
      ./disko.nix
    ];

  # ZFS Support
  boot.supportedFilesystems = [ "zfs" ];
  services.zfs.autoScrub.enable = true; # Recommended for ZFS health
  services.zfs.autoSnapshot.enable = true; # Uncomment to enable automatic snapshots
  services.zfs.autoSnapshot.frequent = 4; # How many frequent snapshots to keep
  services.zfs.autoSnapshot.hourly = 24;
  services.zfs.autoSnapshot.daily = 7;
  services.zfs.autoSnapshot.weekly = 4;
  services.zfs.autoSnapshot.monthly = 6;

  # ZFS requires a unique hostId for each machine.
  # Generate one with `head -c4 /dev/urandom | od -A n -t x1 | tr -d ' \n'`
  # Or use an existing unique machine ID if you have one.
  networking.hostId = "80b2c55c"; # Replace with a unique ID for your host, e.g., generated by the command above

  # Optionally, limit ZFS ARC (cache) size if you have memory constraints
  boot.zfs.arcMaxBytes = 16 * 1024 * 1024 * 1024; # 16GB limit

  # ---------------------------------------------------------------------------
  # X11
  services.xserver.enable = enableXServer;
  services.xserver.autorun = enableXServer;
   
  # Enable the GNOME Desktop Environment.
  services.xserver.displayManager.gdm.enable = enableXServer;
  services.xserver.desktopManager.gnome.enable = true;

  # ---------------------------------------------------------------------------
  system.stateVersion = systemStateVersion; # no touch
}

