[[session]]
name = "dotfiles"
path = "~/nix/"
startup_command = "nvim"
# startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "neovim config"
path = "~/.config/nvim/"
startup_command = "nvim"
