
# Yank file to clipboard
[[manager.prepend_keymap]]
on  = [ "y" ]
run = [ '''
	shell 'cb copy "$@"' --confirm
''', "yank" ]
desc = "Yank to clipboard"

# [max-preview.yazi] Maximize preview
[[manager.prepend_keymap]]
on   = "T"
run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on   = [ "F","g" ]
run  = "plugin fg --args='rg'"
desc = "find by content"

[[manager.prepend_keymap]]
on   = [ "F","a" ]
run  = "plugin fg --args='rga'"
desc = "find file by content (ripgrep-all)"

[[manager.prepend_keymap]]
on   = [ "F","f" ]
run  = "plugin fg --args='fzf'"
desc = "find by filenames"

[[manager.prepend_keymap]]
on   = [ "F","d" ]
run  = "plugin fg --args='fd'"
desc = "find directories only"

[[manager.prepend_keymap]]
on = [ "P" ]
run = '''
  shell --confirm 'qlmanage -p "$@"'
'''
desc = "Preview"
for = "macos"

# Don't go into normal mode when pressing Esc
[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run  = "close"
desc = "Cancel input"
