[manager]
sort_by = "mtime"
sort_reverse = false
sort_dir_first = false

[preview]
image_delay = 0

[opener]
# append_edit = [
#     { run = 'cursor "$@"', 	desc = "Cursor", 		block = true, for = "unix" },
# ]
edit = [
	{ run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
    { run = 'cursor "$@"', 	desc = "Cursor", 		block = true, for = "unix" },
    { run = 'zed "$@"', 	desc = "Zed", 		    block = true, for = "unix" },
	{ run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
	{ run = 'code -w %*', block = true,  desc = "code (block)",   for = "windows" },
]