#!/usr/bin/env bash
set -euo pipefail

# Install NixOS with the host identity generated by host-key.sh; erases the
# target disk.

usage() {
	echo "Usage: $0 <hostname> <ssh-target>   e.g. $0 portal root@1.2.3.4" >&2
	exit 2
}

(($# == 2)) || usage
host=$1
target=$2
repo_root=$(git rev-parse --show-toplevel)
encrypted_key=$repo_root/secrets/host-keys/$host.key.sops
public_key=$repo_root/secrets/host-keys/$host.pub

if [[ ! -f $encrypted_key || ! -f $public_key ]]; then
	echo "No host key for '$host' in secrets/host-keys/. Run: just host-key $host" >&2
	exit 1
fi

echo "This will ERASE the disk on $target and install '$host' from this flake."
read -r -p "Type $host to continue: " confirmation
if [[ $confirmation != "$host" ]]; then
	echo "Confirmation did not match; aborting." >&2
	exit 1
fi

extra_files=$(mktemp -d)
trap 'rm -rf "$extra_files"' EXIT
install -d -m 755 "$extra_files/etc/ssh"
sops decrypt "$encrypted_key" >"$extra_files/etc/ssh/ssh_host_ed25519_key"
cp "$public_key" "$extra_files/etc/ssh/ssh_host_ed25519_key.pub"
chmod 600 "$extra_files/etc/ssh/ssh_host_ed25519_key"
chmod 644 "$extra_files/etc/ssh/ssh_host_ed25519_key.pub"

nix develop -c nixos-anywhere --flake "$repo_root#$host" \
	--target-host "$target" \
	--extra-files "$extra_files" \
	--build-on remote
