nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: delta --diff-so-fancy --paging=never

# git:
#   paging:
#     colorArg: always
#     pager: diff-so-fancy

# git:
#   paging:
#     externalDiffCommand: difft --color=always

os:
  copyToClipboardCmd: printf "\033]52;c;$(printf {{text}} | base64)\a" > /dev/tty
