name: Update Repo Tree
# Triggers: Manual dispatch only
on:
  push:
    branches: [main]
  workflow_dispatch:
# Permissions: Write access to commit changes
permissions:
  contents: write
# Environment: NTFY topic
env:
  NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
jobs:
  tree:
    runs-on: ubuntu-latest
    name: readme-tree
    steps:
      # Checkout Repo
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: DeterminateSystems/nix-installer-action@main
      # Notifications
      - uses: ./.github/actions/ntfy-notify
        if: always()
        with:
          topic: ${{ secrets.NTFY_TOPIC }}
          title: "[Github] Updated Repo Tree"
      # Generate tree and update README
      - name: Generate and update tree
        run: |
          nix run nixpkgs#tree -- -a -I '.git|.direnv' > new_tree.txt
          nix run nixpkgs#python3 -- -c "
          import re
          with open('README.md', 'r') as f:
              content = f.read()
          with open('new_tree.txt', 'r') as f:
              tree = f.read()
          new_content = re.sub(
              r'(<!-- readme-tree start -->).*?(<!-- readme-tree end -->)',
              r'\1\n```\n' + tree + '```\n\2',
              content,
              flags=re.DOTALL
          )
          with open('README.md', 'w') as f:
              f.write(new_content)
          "
          rm new_tree.txt
      # Commit / Push
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "docs: update repository tree structure"
          commit_user_name: "GitHub Action"
          commit_user_email: "action@github.com"
