name: Update Repo Tree
# Triggers: Manual dispatch only
on:
  push:
    branches: [main]
  workflow_dispatch:
# Permissions: Write access to commit changes
permissions:
  contents: write
# Environment: NTFY topic
env:
  NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
jobs:
  tree:
    runs-on: ubuntu-latest
    name: readme-tree
    steps:
      # Checkout Repo
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: DeterminateSystems/nix-installer-action@main
      # Generate tree and update README
      - name: Generate and update tree
        run: |
          nix run nixpkgs#tree -- -a -I '.git|.direnv' > new_tree.txt
          nix run nixpkgs#perl -- -i -pe '
            BEGIN { undef $/; }
            s|<!-- readme-tree start -->.*?<!-- readme-tree end -->|
              "<!-- readme-tree start -->\n```\n" .
              do { open my $fh, "<", "new_tree.txt"; local $/; <$fh> } .
              "```\n<!-- readme-tree end -->"
            |se;
          ' README.md
          rm new_tree.txt
      # Commit / Push
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "docs: update repository tree structure"
          commit_user_name: "GitHub Action"
          commit_user_email: "action@github.com"

  notify:
    runs-on: ubuntu-latest
    name: notify-status
    needs: tree
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ntfy-notify
        with:
          topic: ${{ secrets.NTFY_TOPIC }}
          title: "[Github] ${{ github.workflow }} - ${{ needs.tree.result == 'success' && 'SUCCESS' || 'FAILED' }}"
          message: "Tree update job completed with status: ${{ needs.tree.result }}"
