name: Update Repo Tree
# Triggers: Manual dispatch only
on:
  push:
    branches: [main]
  workflow_dispatch:
# Permissions: Write access to commit changes
permissions:
  contents: write
# Environment: NTFY topic
env:
  NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
jobs:
  tree:
    runs-on: ubuntu-latest
    name: readme-tree
    steps:
      # Checkout Repo
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      # Notifications
      - uses: ./.github/actions/ntfy-notify
        if: always()
        with:
          topic: ${{ secrets.NTFY_TOPIC }}
          title: "[Github] Updated Repo Tree"
      # Generate tree and update README
      - name: Generate and update tree
        run: |
          # Generate tree structure
          tree -a -I '.git|.direnv' > tree_output.tmp

          # Update README between markers
          sed -i '/<!-- readme-tree start -->/,/<!-- readme-tree end -->/c\
          <!-- readme-tree start -->\
          ```\
          '"$(cat tree_output.tmp | sed 's/$/\\/')"'\
          ```\
          <!-- readme-tree end -->' README.md

          # Clean up temp file
          rm -f tree_output.tmp
      # Commit / Push
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "docs: update repository tree structure"
          commit_user_name: "GitHub Action"
          commit_user_email: "action@github.com"
